### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by dkwstas** [mitchfizz05/Sphinx#4]
Hello, could someone please mention the dependencies/requirements for this project? I acknowledge that it has been abandoned, but I really want to run it as an experiment. When I run the "composer install" command I encounter several errors, even after running "composer dumpauto". Thanks in advance!

**Comment by mibblemerps** [comment]
Apologies for not getting back to you earlier.

Maybe if you provided the output from composer I could help. I'm assuming some dependencies are broken or something. Try using PHP 5.5 if you're not already.

**Comment by dkwstas** [comment]
Hello, sorry for not keeping the issue updated but I actually got it working a long time ago. Thank you once again! Have a great day :)
